// Code generated by "stringer -type=WeatherCondition"; DO NOT EDIT

package main

import "fmt"

const _WeatherCondition_name = "CLEARRAINPARTLY_CLOUDYMOSTLY_CLOUDYTHUNDERTHUNDER_RAINTORNADOSNOWWINDYFOGGYHAZEUNKNOWN_WEATHER"

var _WeatherCondition_index = [...]uint8{0, 5, 9, 22, 35, 42, 54, 61, 65, 70, 75, 79, 94}

func (i WeatherCondition) String() string {
	if i >= WeatherCondition(len(_WeatherCondition_index)-1) {
		return fmt.Sprintf("WeatherCondition(%d)", i)
	}
	return _WeatherCondition_name[_WeatherCondition_index[i]:_WeatherCondition_index[i+1]]
}
